<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>TuneBar.Launcher</RootNamespace>
    <AssemblyName>TuneBar</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TuneBar.Shared\TuneBar.Shared.csproj" />
  </ItemGroup>

</Project>
